[tool.poetry]
name = "r2r"
version = "0.4.0"
description = "Repeat Until Recall - a simple, yet powerful, flashcard app"
authors = ["Pacharapol Withayasakpunt <polv@polv.cc>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pyppeteer = "^0.2.6"
toml = "^0.10.2"
click = "^8.0.1"
PyYAML = "^5.4.1"
peewee = "^3.14.4"

[tool.poetry.dev-dependencies]
black = {version = "^21.8b0", allow-prereleases = true}
pyinstaller = "^4.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
